# Generated by Django 4.1.6 on 2023-03-27 08:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_banner', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo1', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото1')),
                ('photo2', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото4')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Адреса баннеров',
                'verbose_name_plural': 'Адреса баннеров',
                'ordering': ['time_create', 'address_banner'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакты клиентов',
                'verbose_name_plural': 'Контакты клиентов',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_oranization', models.CharField(max_length=80)),
                ('contact_face', models.CharField(default=' ', max_length=100)),
                ('logotip', models.ImageField(default=' ', upload_to='photos/%Y/%m/%d/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(default=' ', max_length=500)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kontact',
                'verbose_name_plural': 'Kontact',
                'ordering': ['time_create', 'name_oranization'],
            },
        ),
    ]
