# Generated by Django 4.1.6 on 2023-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['time_create', 'name_oranization'], 'verbose_name': 'Kontact', 'verbose_name_plural': 'Данные нашей организации'},
        ),
        migrations.AddField(
            model_name='adressadvertising',
            name='area',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
